In [1]:
import numpy as np
import random 
np.random.seed(0)



In [2]:
class FunctionFactory():
    pass


In [3]:
def generate_random_nondecreasing_function( number_of_points,  ):
    x, y = [], []
    for i in range(number_of_points):
        x_incr, y_incr = random.random(), random.random(), 
        if len(x) == 0:
            x.append(x_incr)
            y.append(y_incr)
        else:
            x.append(x_incr+x[-1])
            y.append(y_incr+y[-1])
    x = np.array(x)
    y = np.array(y)
    print(x)
    print(y)
    def final_funcion( x, y, t ):
        assert x[0] <= t
        assert x[-1] >= t
        
    return final_funcion

def generate_random_convex_function():
    x_points = np.random.randint(low=1, high=20, size=4)
    x_points.sort()
    x_points = np.append(0, x_points)  # the first 0 point is 0

    slopes = np.add.accumulate(np.random.random(size=3))
    slopes = np.append(0,slopes)  # the first slope is 0

    y_incr = np.ediff1d(x_points)*slopes
    y_points = np.add.accumulate(y_incr)
    y_points = np.append(0,y_points)  # the first y values is 0

    print(x_points)
    print(slopes)
    print(y_points)
    def final_function( x ):
        y = 0
        return y
    return final_function

def generate_several_rcf():
    pass





In [4]:
f = generate_random_nondecreasing_function( 10 )
f( -3 )


[0.2068572  1.19850759 1.49917248 1.72868122 1.93945484 2.91276355
 2.97135678 3.73334385 4.47231264 4.49690976]
[0.59988198 0.63794007 1.43301104 2.08480177 2.34742583 3.14866806
 3.66859697 4.50829217 4.7732793  5.02003516]


TypeError: generate_random_nondecreasing_function.<locals>.final_funcion() missing 2 required positional arguments: 'y' and 't'

In [5]:
for i in range(10):
    f = generate_random_convex_function()
    f( 3 )



[ 0  1  4 13 16]
[0.         0.85794562 1.70519736 2.32876105]
[ 0.          0.          2.57383685 17.92061306 24.90689622]
[ 0  5  7 13 19]
[0.         0.38344152 1.17516656 1.70406148]
[ 0.          0.          0.76688304  7.81788238 18.04225124]
[ 0  6  9 14 18]
[0.         0.0871293  0.1073477  0.93996754]
[0.         0.         0.2613879  0.79812638 4.55799656]
[ 0  1 16 16 19]
[0.         0.47360805 1.2745188  1.79499628]
[ 0.          0.          7.10412068  7.10412068 12.48910951]
[ 0  1  2  8 15]
[0.         0.14335329 1.0880222  1.60987053]
[ 0.          0.          0.14335329  6.67148651 17.9405802 ]
[ 0  3  4 12 19]
[0.         0.13521817 0.45935918 0.60903405]
[0.         0.         0.13521817 3.81009162 8.07332996]
[ 0  5  9 16 18]
[0.         0.6818203  1.0413282  1.47836015]
[ 0.          0.          2.7272812  10.01657859 12.9732989 ]
[ 0  2  4  8 10]
[0.         0.65314004 0.82404962 1.18220179]
[0.         0.         1.30628007 4.60247856 6.96688213]
[ 0  1  4 13 15