In [1]:
from world import World
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [2]:
world = World({'debugging': 1})
world.run()
game = world.game
for agent in game.agents:
    agent = agent
water = list(game.resources.objects.values())[0]
for crop in game.crops:
    crop = crop
for resource in game.resources:
    if resource.name == "Booster":
        booster = resource


{'T4Ot?`koIPKq8Q?lj7|D': {}}
{'_r7f0@?|w5WHufufxa3n': {}, '4M(wuX@w+WQi^4sB8mcP': {}, '$PHf!XK*wlsD1$TM3PXx': {}, '#YEdÇ2)2ffHyum9NVqVC': {}, 'fU#VJ8?l0$8zKQXWz7pu': {}}
{'gf8r*sSaSf_P:?6wVAwe': {}, 'X1y1?ps$Jlk+X(etH5OK': {}, 'B)I=:)k3D_50t%çh0st-': {}, 'qB+w?9c0@PBGz8=reJ:1': {}, 'ppB0E2N`e2A16^Y0vkzs': {}}
{'#5kt%\\#OH0sJsHVeC2#+': {}, '%lçyM*MMuWp0IoEm09x_': {}}


In [3]:
agent.initialize_nn()


In [5]:
print(agent.money)
for epoch in range(10):
    game.step()
    
print(agent.money)


tensor(-254868., grad_fn=<SubBackward0>)
tensor([ 24.,   0., 212.,  53.,   0., 216.,   0.,   0.,  69., 188.],
       grad_fn=<RoundBackward0>)
tensor([ 27.,   0., 217.,  53.,   0., 222.,   0.,   0.,  73., 190.],
       grad_fn=<RoundBackward0>)
tensor([ 25.,   0., 223.,  52.,   0., 225.,   0.,   0.,  72., 195.],
       grad_fn=<RoundBackward0>)
tensor([ 24.,   0., 224.,  52.,   0., 225.,   0.,   0.,  74., 194.],
       grad_fn=<RoundBackward0>)
tensor([ 26.,   0., 224.,  55.,   0., 227.,   0.,   0.,  75., 194.],
       grad_fn=<RoundBackward0>)
tensor([ 26.,   0., 234.,  53.,   0., 237.,   0.,   0.,  83., 203.],
       grad_fn=<RoundBackward0>)
tensor([ 26.,   0., 234.,  53.,   0., 237.,   0.,   0.,  85., 203.],
       grad_fn=<RoundBackward0>)
tensor([ 27.,   0., 236.,  54.,   0., 240.,   0.,   0.,  89., 203.],
       grad_fn=<RoundBackward0>)
tensor([ 24.,   0., 242.,  52.,   0., 242.,   0.,   0.,  89., 207.],
       grad_fn=<RoundBackward0>)
tensor([ 28.,   0., 244.,  55.,   0., 247

In [6]:
actions = agent.figure_out_decision()
print(actions)
real_actions = torch.round(actions*100)
print(real_actions)

# state_data = agent.get_state_data()
# features = torch.tensor(state_data, dtype=torch.float32)
# # labels = torch.tensor(actions, dtype=torch.float32)  
# actions = agent.nn(features)
# print(actions)
# agent.nn( [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ] )




tensor([0.2003, 0.2893, 0.3275, 0.2480, 0.2866, 0.1388, 0.0000, 0.1026, 0.9055,
        0.6001], grad_fn=<ReluBackward0>)
tensor([200., 289., 328., 248., 287., 139.,   0., 103., 906., 600.],
       grad_fn=<RoundBackward0>)


In [8]:
def custom_loss_function( agent, game ):
    # should i game.step()
    initial_money = agent.money
    game.step()
    final_money = agent.money
    loss = final_money - initial_money
    return loss



In [36]:
custom_loss_function( agent, game )




1330
1295


-35

In [38]:
for epoch in range(100):
    print(custom_loss_function( agent, game))

2165
2130
-35
2130
2115
-15
2115
2090
-25
2090
2055
-35
2055
2040
-15
2040
2025
-15
2025
2385
360
2385
2370
-15
2370
2345
-25
2345
2310
-35
2310
2295
-15
2295
2270
-25
2270
2245
-25
2245
2210
-35
2210
2185
-25
2185
2160
-25
2160
2135
-25
2135
2425
290
2425
2400
-25
2400
2375
-25
2375
2360
-15
2360
2335
-25
2335
2310
-25
2310
2295
-15
2295
2270
-25
2270
2235
-35
2235
2210
-25
2210
2185
-25
2185
2510
325
2510
2495
-15
2495
2480
-15
2480
2465
-15
2465
2430
-35
2430
2415
-15
2415
2380
-35
2380
2365
-15
2365
2330
-35
2330
2315
-15
2315
2290
-25
2290
2580
290
2580
2565
-15
2565
2520
-45
2520
2485
-35
2485
2450
-35
2450
2425
-25
2425
2410
-15
2410
2395
-15
2395
2360
-35
2360
2325
-35
2325
2300
-25
2300
2660
360
2660
2635
-25
2635
2610
-25
2610
2585
-25
2585
2570
-15
2570
2555
-15
2555
2540
-15
2540
2515
-25
2515
2480
-35
2480
2445
-35
2445
2420
-25
2420
2780
360
2780
2745
-35
2745
2720
-25
2720
2705
-15
2705
2680
-25
2680
2655
-25
2655
2620
-35
2620
2595
-25
2595
2570
-25
2570
2535
-35
2535
2

In [4]:
for _ in range( 100 ):
    game.step()

In [ ]:
print()