In [1]:
from world import World
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [2]:
world = World({'debugging': 1})
world.run()
game = world.game
for agent in game.agents:
    agent = agent
water = list(game.resources.objects.values())[0]
for crop in game.crops:
    crop = crop
for resource in game.resources:
    if resource.name == "Booster":
        booster = resource
    booster.distribution = ()



{'FDCZQ^rtevZ*m8foIJt8': {}}
{'xrNF8^epKy*çmO93xD@L': {}, 'eY%6lq-moA?ErDl\\qKv2': {}, 'jv=?6Ph^9)oEzYkgwm3C': {}, 'Lt0kc%pfsh*_b!|oidx|': {}, '7`g97yM4qQejh7=3Syçm': {}}
{'xçy@?=#jqad7sLwx!REs': {}, 'x78E8lxÇ6mrÇl@aPçAç+': {}, '16d\\hATtL!*)LNq=0vo_': {}, '\\y#UIçÇTM_rDuOEvJ6ZL': {}, '|K2O`+wn`3!N6+zvU7Vj': {}}
{'ZiSxDAçuFC^C3vfqS6O9': {}, '6pljs(iSxH_\\kA4FFNoO': {}}


In [3]:
agent.initialize_nn()


In [7]:
print(agent.money)
for epoch in range(10):
    game.step()
    
print(agent.money)


1000
tensor([1.0627, 0.0000, 0.7921, 0.0000, 0.2845, 0.0000, 0.9621, 0.0000, 1.8340,
        0.0000], grad_fn=<ReluBackward0>)
tensor([106.,   0.,  79.,   0.,  28.,   0.,  96.,   0., 183.,   0.],
       grad_fn=<RoundBackward0>)
tensor([1.0204, 0.0000, 0.7873, 0.0000, 0.2779, 0.0000, 0.9409, 0.0000, 1.7851,
        0.0000], grad_fn=<ReluBackward0>)
tensor([102.,   0.,  79.,   0.,  28.,   0.,  94.,   0., 179.,   0.],
       grad_fn=<RoundBackward0>)
tensor([0.9905, 0.0000, 0.7690, 0.0000, 0.2674, 0.0000, 0.9109, 0.0000, 1.7333,
        0.0000], grad_fn=<ReluBackward0>)
tensor([ 99.,   0.,  77.,   0.,  27.,   0.,  91.,   0., 173.,   0.],
       grad_fn=<RoundBackward0>)
tensor([0.8612, 0.0000, 0.6657, 0.0000, 0.2691, 0.0000, 0.7626, 0.0000, 1.5606,
        0.0000], grad_fn=<ReluBackward0>)
tensor([ 86.,   0.,  67.,   0.,  27.,   0.,  76.,   0., 156.,   0.],
       grad_fn=<RoundBackward0>)
tensor([0.8251, 0.0000, 0.6513, 0.0000, 0.2588, 0.0000, 0.7501, 0.0000, 1.5063,
        0.0000], gr

In [6]:
actions = agent.figure_out_decision()
print(actions)
real_actions = torch.round(actions*100)
print(real_actions)

# state_data = agent.get_state_data()
# features = torch.tensor(state_data, dtype=torch.float32)
# # labels = torch.tensor(actions, dtype=torch.float32)  
# actions = agent.nn(features)
# print(actions)
# agent.nn( [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ] )




tensor([0.2003, 0.2893, 0.3275, 0.2480, 0.2866, 0.1388, 0.0000, 0.1026, 0.9055,
        0.6001], grad_fn=<ReluBackward0>)
tensor([200., 289., 328., 248., 287., 139.,   0., 103., 906., 600.],
       grad_fn=<RoundBackward0>)


In [4]:
def custom_loss_function( agent, game ):
    # should i game.step()
    initial_money = agent.money
    game.step()
    final_money = agent.money
    loss = final_money - initial_money
    return loss



In [36]:
custom_loss_function( agent, game )




1330
1295


-35

In [8]:
for epoch in range(100):
    print(custom_loss_function( agent, game))

NameError: name 'custom_loss_function' is not defined

In [4]:
for _ in range( 100 ):
    game.step()

In [ ]:
print()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\51053667\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


['On', 'a', '$', '50,000', 'mortgage', 'of', '30', 'years', 'at', '8', 'percent', ',', 'the', 'monthly', 'payment', 'would', 'be', '$', '366.88', '.']
<class 'list'>
